Update samples: bump AGP version to 8.2.0; update NDK version.
`samples/unittest` is still broken on macOS with architecture
mismatches like:
```
com.nishtahir.androidrust.ExampleUnitTest > testViaJNI FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.nishtahir.androidrust.MainActivity
        at com.nishtahir.androidrust.ExampleUnitTest.testViaJNI(ExampleUnitTest.java:30)

        Caused by:
        java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /Users/nalexander/Library/Caches/JNA/temp/jna17483397431938007410.tmp: dlopen(/Users/nalexander/Library/Caches/JNA/temp/jna17483397431938007410.tmp, 0x0001): tried: '/Users/nalexander/Library/Caches/JNA/temp/jna17483397431938007410.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64e.v1' or 'arm64' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/nalexander/Library/Caches/JNA/temp/jna17483397431938007410.tmp' (no such file), '/Users/nalexander/Library/Caches/JNA/temp/jna17483397431938007410.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e' or 'arm64e.v1' or 'arm64' or 'arm64')) [in thread "SDK 21 Main Thread"]
            at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
            at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
            at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
            at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
            at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
            at java.base/java.lang.Runtime.load0(Runtime.java:755)
            at java.base/java.lang.System.load(System.java:1970)
            at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
            at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
            at com.sun.jna.Native.<clinit>(Native.java:195)
            at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
            at com.nishtahir.androidrust.MainActivity.<clinit>(MainActivity.java:28)
            at com.nishtahir.androidrust.ExampleUnitTest.testViaJNA(ExampleUnitTest.java:36)
```